# Generated by Django 5.0.6 on 2024-06-30 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id_serie', models.AutoField(db_column='id_genero', primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='libros',
            name='serie',
        ),
        migrations.AddField(
            model_name='libros',
            name='id_serie',
            field=models.ForeignKey(db_column='id_serie', default=1, on_delete=django.db.models.deletion.CASCADE, to='libros.serie'),
            preserve_default=False,
        ),
    ]
