# Generated by Django 5.0.6 on 2024-06-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_alter_libros_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
